---
apiVersion: v1
kind: Namespace
metadata:
  name: reddit-notifier
---
apiVersion: v1
kind: Secret
metadata:
  name: reddit-notifier
  namespace: reddit-notifier
type: Opaque
stringData:
  REDDIT_SUBREDDIT: "usenetinvites"
  REDDIT_MATCHER: '\[[o|O]\].*(([d|D]runk)|([d|D]og)).*'
  REDDIT_DISCORD_URL: "yours"
  REDDIT_USERNAME: "yours"
  REDDIT_PASSWORD: "yours"
  REDDIT_APP_ID: "yours"
  REDDIT_APP_SECRET: "yours"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reddit-notifier
  name: reddit-notifier
  namespace: reddit-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-notifier
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reddit-notifier
    spec:
      containers:
      - image: swyytch/reddit-notifier:latest
        imagePullPolicy: Always
        name: reddit-notifier
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Ki
        env:
        - name: REDDIT_SUBREDDIT
          valueFrom:
            secretKeyRef:
              name: reddit-notifier
              key: REDDIT_SUBREDDIT
        - name: REDDIT_MATCHER
          valueFrom:
            secretKeyRef:
              name: reddit-notifier
              key: REDDIT_MATCHER
        - name: REDDIT_DISCORD_URL
          valueFrom:
            secretKeyRef:
              name: reddit-notifier
              key: REDDIT_DISCORD_URL
        - name: REDDIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: reddit-notifier
              key: REDDIT_USERNAME
        - name: REDDIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reddit-notifier
              key: REDDIT_PASSWORD
        - name: REDDIT_APP_ID
          valueFrom:
            secretKeyRef:
              name: reddit-notifier
              key: REDDIT_APP_ID
        - name: REDDIT_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: reddit-notifier
              key: REDDIT_APP_SECRET
        - name: REDDIT_LOG_IN
          value: "true"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
